[package]
name = "feldspar2"
version = "0.1.0"
authors = ["zmeadows <zmeadows@gmail.com>"]

[dependencies]
colored = "1.6"
log = "0.4.1"
pretty_env_logger = "0.2.3"
bitflags = "1.0.3"
prettytable-rs = "^0.6"
